export const SET_TEST = 'SET_TEST';
export const GET_INITHOLIDAY = 'GET_INITHOLIDAY';
export const GET_SCHOOLYEARINFO = 'GET_SCHOOLYEARINFO';

export const GET_USERINFO = 'GET_USERINFO';
export const GET_LANGUAGE = 'GET_LANGUAGE';

export const GET_AUTOLOGINFINISH = 'GET_AUTOLOGINFINISH';
export const SET_MEMOSIDE = 'SET_MEMOSIDE';
export const SET_MEMOSIDELIST = 'SET_MEMOSIDELIST';
