export const SET_TEST = 'SET_TEST';
export const GET_INITHOLIDAY = 'GET_INITHOLIDAY';
export const GET_SCHOOLYEARINFO = 'GET_SCHOOLYEARINFO';

export const GET_USERINFO = 'GET_USERINFO';
export const GET_LANGUAGE = 'GET_LANGUAGE';
