export const SET_TEST = 'SET_TEST';
export const SET_INITHOLIDAY = 'SET_INITHOLIDAY';
export const SET_SCHOOLYEARINFO = 'SET_SCHOOLYEARINFO';

export const GET_USERINFO = 'GET_USERINFO';
export const GET_LANGUAGE = 'GET_LANGUAGE';
